### ISSUE TITLE
Sprockets::FileNotFound exception

### ISSUE THREAD

**Issue by francistm** [TomKnig/flakes-rails#1]
I have tried this gem, but it always throw `couldn't find file 'flakes-rails/min'` exception.

After check the file https://github.com/tomknig/flakes-rails/blob/master/vendor/assets/stylesheets/flakes-rails/index.css, there's actully no `flakes-rails/min` files.

I have install the `npm`and `bower`, should I do something else, like download flakes by myself?

Thanks a lot :smiley:

**Comment by tomknig** [comment]
Thank you for reporting that one! :)
I fixed it in 9131a9205b79fc0bd3e1c9972bed6eb7455c7afc. It should work after you `bundle update flakes-rails`.

Cheers,
Tom
